dataset:
        train_batch_size: 32
        eval_batch_size: 32

train:
        optimizer: Adam
        num_epochs: 10

encoder:
        type: hre
        dropout: 0.5
        rnn_hidden_size: 512
        embed_size: 1024
        num_layers: 4
        use_im: True
        img_embed_size: 512
        num_rounds: 5
        start_token: null
        end_token: null

decoder:
        type: gen
        dropout: 0.5
        rnn_hidden_size: 512
        embed_size: 1024
        num_layers: 4
        start_token: null
        end_token: null

save_dir: "checkpoints"
