dataset:
        train_batch_size: 32
        eval_batch_size: 32

train:
        optimizer: Adam
        num_epochs: 10

questioner:
        encoder:
                type: hre
                dropout: 0.5
                rnnHiddenSize: 512
                embedSize: 1024
                numLayers: 4
                useIm: True
                imgEmbedSize: 512
                numRounds: 5

        decoder:
                type: gen
                dropout: 0.5
                rnnHiddenSize: 512
                embedSize: 1024
                numLayers: 4

answerer:
        embed_dim: 1024
        image_embed_dim: 512
        hidden_dim: 512
        rnn_output_dim: 512
        output_dim: 1000
