dataset:
        train_batch_size: 32
        eval_batch_size: 32

train:

questioner:
        encoder:
                type: hre
                dropout: 0.5
        decoder:
                type: gen

